# Form implementation generated from reading ui file '.\QT_ui\gui.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets, QtSvg
from PyQt6.QtCore import QPoint, QTime, QTimer
from PyQt6.QtGui import QColor, QPolygon, QPainter
import re
import socket
import threading
import time
import json

class AnalogClock(QtWidgets.QWidget):
    secondHand = QPolygon([
        QPoint(7, 8),
        QPoint(-7, 8),
        QPoint(0, -95)
    ])
    hourHand = QPolygon([
        QPoint(7, 8),
        QPoint(-7, 8),
        QPoint(0, -50)
    ])
    minuteHand = QPolygon([
        QPoint(7, 8),
        QPoint(-7, 8),
        QPoint(0, -70)
    ])
    hourColor = QColor(127, 0, 127)
    minuteColor = QColor(0, 100, 250, 200)
    secondColor = QColor(195, 0, 0, 150)

    def __init__(self, parent=None):
        super(AnalogClock, self).__init__(parent)
        timer = QTimer(self)
        timer.timeout.connect(self.update)
        timer.start(1000)
        self.setMinimumSize(200, 200)

    def paintEvent(self, event):
        side = min(self.width(), self.height())
        time = QTime.currentTime()
        painter = QPainter(self)
        painter.translate(self.width() / 2, self.height() / 2)
        painter.scale(side / 200, side / 200)

        #vẽ 12 vạch 12 số
        for i in range(12):
            painter.drawLine(88, 0, 96, 0)
            painter.rotate(30.0)

        #vẽ 60 vạch phút
        for j in range(60):
            if (j % 5) != 0:
                painter.drawLine(92, 0, 96, 0)
            painter.rotate(6.0)

        # Vẽ giờ
        painter.setBrush(AnalogClock.hourColor)
        painter.save()
        painter.rotate(30.0 * (time.hour() + time.minute() / 60.0))
        painter.drawConvexPolygon(AnalogClock.hourHand)
        painter.restore()

        # Vẽ phút
        painter.setBrush(AnalogClock.minuteColor)
        painter.save()
        painter.rotate(6.0 * (time.minute() + time.second() / 60.0))
        painter.drawConvexPolygon(AnalogClock.minuteHand)
        painter.restore()

        # Vẽ giây
        painter.setBrush(AnalogClock.secondColor)
        painter.save()
        painter.rotate(360 * (time.second() / 60.0))
        painter.drawConvexPolygon(AnalogClock.secondHand)
        painter.restore()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("CLOCK TCP")
        # MainWindow.resize(622, 790)
        MainWindow.setFixedSize(650, 650) #790
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 90, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.areaTxt = QtWidgets.QComboBox(parent=self.centralwidget)
        self.areaTxt.setGeometry(QtCore.QRect(50, 80, 201, 31))
        self.areaTxt.setObjectName("areaTxt")


        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 90, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.timeLCDNumber = QtWidgets.QLCDNumber(parent=self.centralwidget)
        self.timeLCDNumber.setGeometry(QtCore.QRect(60, 200, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.timeLCDNumber.setFont(font)
        self.timeLCDNumber.setStyleSheet("color: red;")
        self.timeLCDNumber.setDigitCount(10)
        self.timeLCDNumber.setObjectName("timeLCDNumber")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.ipServerTxt = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ipServerTxt.setGeometry(QtCore.QRect(140, 40, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ipServerTxt.setFont(font)
        self.ipServerTxt.setObjectName("ipServerTxt")

        self.label_port = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_port.setGeometry(QtCore.QRect(260, 50, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_port.setFont(font)
        self.label_port.setObjectName("label_port")
        self.portServerTxt = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.portServerTxt.setGeometry(QtCore.QRect(300, 40, 60, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.portServerTxt.setFont(font)
        self.portServerTxt.setObjectName("portServerTxt")

        self.connectBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.connectBtn.setGeometry(QtCore.QRect(365, 40, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.connectBtn.setFont(font)
        self.connectBtn.setObjectName("connectBtn")
        self.statusConnectLb = QtWidgets.QLabel(parent=self.centralwidget)
        self.statusConnectLb.setGeometry(QtCore.QRect(450, 50, 200, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.statusConnectLb.setFont(font)
        self.statusConnectLb.setObjectName("statusConnectLb")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.countryTxt = QtWidgets.QComboBox(parent=self.centralwidget)
        self.countryTxt.setGeometry(QtCore.QRect(320, 80, 201, 31))
        self.countryTxt.setObjectName("countryTxt")

        self.dateTxt = QtWidgets.QLabel(parent=self.centralwidget)
        self.dateTxt.setGeometry(QtCore.QRect(60, 170, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dateTxt.setFont(font)
        self.dateTxt.setObjectName("dateTxt")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 200, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.requestBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.requestBtn.setGeometry(QtCore.QRect(530, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.requestBtn.setFont(font)
        self.requestBtn.setObjectName("requestBtn")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 140, 301, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(80, 10, 491, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.flagLB = QtWidgets.QLabel(parent=self.centralwidget)
        self.flagLB.setGeometry(QtCore.QRect(270, 170, 111, 51))
        self.flagLB.setObjectName("flagLB")

        #-------------------------------------------------------
        self.load_data_from_file('countries.txt')
        self.dataCountries = self.load_countries_from_file('countries.txt')
        self.dataFlag = self.load_countries_from_json('countries_flag.json')
        self.areaTxt.currentIndexChanged.connect(self.update_country_txt)

        # Thêm đồng hồ vào GUI
        self.clock = AnalogClock(parent=self.centralwidget)
        self.clock.setGeometry(QtCore.QRect(200, 250, 300, 300))  # Điều chỉnh kích thước và vị trí

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 622, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        
        self.statusCloseWindow = False
        self.threadRecvRunning = False
        self.threadTransRunning = False
        self.threadRecvTimeFromServerRunning = False
        self.threadRequestTime = False
        self.region = ''
        self.receiveDate = ''
        self.receiveTime = ''
        self.clientClose = None
        app.aboutToQuit.connect(self.closeEvent)
        self.connectBtn.clicked.connect(self.connectWithServer)
        self.requestBtn.clicked.connect(self.on_country_selected)
        self.requestBtn.clicked.connect(self.requestTime)
        #-------------------------------------------------------

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CLOCK"))

        self.label.setText(_translate("MainWindow", "Area:"))
        self.label_2.setText(_translate("MainWindow", "Country:"))

        self.label_3.setText(_translate("MainWindow", "IPv4 Server connect:"))
        self.label_port.setText(_translate("MainWindow", "Port:"))
        self.connectBtn.setText(_translate("MainWindow", "Connect"))
        self.statusConnectLb.setText(_translate("MainWindow", "Status:"))
        self.label_5.setText(_translate("MainWindow", "Date:"))
        self.dateTxt.setText(_translate("MainWindow", "0:00:0000"))
        self.label_7.setText(_translate("MainWindow", "Time:"))
        self.requestBtn.setText(_translate("MainWindow", "Request"))
        self.label_4.setText(_translate("MainWindow", "RESULTS RETURNED FROM SERVER"))
        self.label_8.setText(_translate("MainWindow", "CLOCK PROGRAM (TCP CLIENT SERVER MODEL)"))
        self.flagLB.setText(_translate("MainWindow", "flag"))

    #-------------------------------------------------------
    
    # def load_data_from_file(self, filename):
    #     area_list = []
    #     country_list = []

    #     # Đọc dữ liệu từ file
    #     with open(filename, 'r') as file:
    #         for line in file:
    #             line = line.strip()  # Xóa khoảng trắng ở đầu và cuối
    #             if line:  # Kiểm tra xem dòng không trống
    #                 try:
    #                     country, area = line.split(": ")
    #                     country = country.strip("'")
    #                     area = area.strip("'")
                        
    #                     area_list.append(country)
    #                     country_list.append(area)
    #                 except ValueError:
    #                     print(f"Lỗi phân tích cú pháp dòng: '{line}'")  # In ra lỗi nếu có
    #                     continue  # Bỏ qua dòng này nếu không thể phân tích

    #     # Cập nhật các item trong areaTxt và countryTxt
    #     for i in range(len(area_list)):
    #         self.areaTxt.addItem(area_list[i])  # Không cần gọi self.tr()
    #         self.countryTxt.addItem(country_list[i])  # Không cần gọi self.tr()


    def load_data_from_file(self, filename):
            self.data = {}  # Khởi tạo dict để lưu trữ dữ liệu

            # Đọc dữ liệu từ file
            with open(filename, 'r') as file:
                for line in file:
                    line = line.strip()
                    if line:
                        try:
                            country, area = line.split(": ")
                            country = country.strip("'")
                            area = area.strip("'")

                            # Tách phần trước và sau dấu '/'
                            area_prefix = area.split('/')[0]
                            country_suffix = area.split('/')[-1]

                            # Thêm vào dict
                            if area_prefix not in self.data:
                                self.data[area_prefix] = []
                            self.data[area_prefix].append(country_suffix)

                        except ValueError:
                            print(f"Lỗi phân tích cú pháp dòng: '{line}'")
                            continue

            # Cập nhật areaTxt
            for area in self.data.keys():
                self.areaTxt.addItem(area)

    def update_country_txt(self):
        selected_area = self.areaTxt.currentText()
        self.countryTxt.clear()  # Xóa các item hiện tại

        if selected_area in self.data:
            # Lọc và thêm các quốc gia tương ứng vào countryTxt
            for country in self.data[selected_area]:
                self.countryTxt.addItem(country)

        # Nếu không có phần sau dấu '/', thêm phần đó vào countryTxt
        elif selected_area:
            self.countryTxt.addItem(selected_area)

    def on_country_selected(self):
        selected_area = self.areaTxt.currentText()
        selected_country = self.countryTxt.currentText()

        selected_country_flag = ""

        if(selected_area == selected_country):
            selected_country_flag = selected_country
        else:
            selected_country_flag =  selected_area + "/" + selected_country

        print(selected_country_flag)
        self.filter_country_by_region(selected_country_flag, self.dataCountries)
        

    
    def load_countries_from_file(self,file_path):
        countries = {}
        with open(file_path, 'r') as file:
            count = 0
            for line in file:
                count = count+1
                
                # Tách tên quốc gia và vị trí
                country, location = line.split(": ")
                country = country.strip().strip("'")
                location = location.strip().strip("'")


                # print(count, ": ", country, "-", location )

                countries[country] = location
                # Nếu quốc gia đã có trong từ điển, thêm vị trí vào danh sách
                # if country in countries:
                #     countries[country].append(location)  # Thêm vị trí vào danh sách
                # else:
                #     countries[country] = [location]  # Khởi tạo danh sách nếu chưa có


            print(count)
        return countries

    def filter_country_by_region(self, region, countries):
        # print(countries)
        # print("--------------------")
        for country, location in countries.items():
            print(location, "====", region)
            if location == region:
                # print("++++", country)
                # path_flag = convert_string()
                country_code = self.get_country_code(country, self.dataFlag)
                # print("-----", country_code)
                if country_code:
                    path_flag = 'svg/' + country_code.lower() + '.svg'
                    # print(f'The country code for {country} is {country_code}, path flag: {path_flag}.')

                    svg_renderer = QtSvg.QSvgRenderer(path_flag)
                    # Lấy kích thước gốc của hình SVG
                    original_size = svg_renderer.defaultSize()
                    aspect_ratio = original_size.width() / original_size.height()

                    # Tính chiều rộng mới dựa trên chiều cao cố định
                    new_height = 51
                    new_width = int(aspect_ratio * new_height)

                    # Tạo một QPixmap với kích thước mới
                    pixmap = QtGui.QPixmap(new_width, new_height)
                    pixmap.fill(QtGui.QColor('transparent'))  # Lấp đầy với màu trong suốt

                    # Vẽ hình SVG lên QPixmap với kích thước mới
                    painter = QtGui.QPainter(pixmap)
                    svg_renderer.render(painter, QtCore.QRectF(0, 0, new_width, new_height))  # Vẽ vào vùng với chiều cao 51
                    painter.end()

                    # Đặt QPixmap vào QLabel
                    self.flagLB.setPixmap(pixmap)
                    break



                else:
                    print(f'Country not found: {country}.')
    
    def load_countries_from_json(self, file_path):
        with open(file_path, 'r') as file:
            countries = json.load(file)
        return countries

    def get_country_code(self, country_name, countries):
        for code, name in countries.items():
            print("xxx" ,code)
            if name.lower() == country_name.lower():
                return code
        return None

    def connectWithServer(self):
        if(self.connectBtn.text() == "Connect"):
            ip = self.ipServerTxt.text()
            port = int(self.portServerTxt.text())

            if is_valid_ipv4(ip) and is_valid_port(int(port)):
                print(ip, ":", port)
                start_thread = threading.Thread(target=self.start_client, args=(ip,int(port)))
                start_thread.start()
                
            else: 
                self.statusConnectLb.setText("IPv4 ERROR")
        else:
            self.connectBtn.setText("Connect")
            self.statusConnectLb.setText("Status: Disconnected")
            self.client.close()
            

    def requestTime(self):
        print("REQUEST TIME BTN EVENT")

        area = self.areaTxt.currentText() 
        country = self.countryTxt.currentText()
        
        if(area == country):
            self.region = area
        else:
            self.region = area +"/" + country
        print(self.region)

        if(self.threadRequestTime == False):
            thread_request_time = threading.Thread(target=self.client_start_request_time)
            thread_request_time.start()
            self.threadRequestTime = True
        else:
            print("client_start_request_time: running")
        

    def client_start_request_time(self):
        
        thread = threading.Thread(target=self.client_receive_time_from_server, args=(self.client,))
        thread.start()
        running = True
        while running:
            # message = input("Enter message: ")
            if(self.statusCloseWindow):
                self.statusConnectLb.setText("Status: Disconnect")
                # self.connectBtn.setEnabled(True)
                running = False
            time.sleep(1)
            message = self.region
            print("client_start_request_time:", message)
            self.client.send(message.encode('utf-8'))
        self.threadRequestTime = False
        self.client.close()

    def client_receive_time_from_server(self, client_socket):
        
        self.threadRecvTimeFromServerRunning = True
        while self.threadRecvTimeFromServerRunning:
            try:
                print("client_receive_time_from_server")
                message = self.client.recv(1024).decode('utf-8')
                print("MESS: ",message)
                if message:
                    print(message)
                    self.receiveDate = message
                    if(self.receiveDate == "Server received: xconnected"):
                        self.dateTxt.setText("00/00/0000")
                    else:
                        
                        r_date, r_time = self.receiveDate.split('*')
                        r_date = r_date.strip()
                        r_time = r_time.strip()
                        r_day, r_month, r_year = r_date.split('-')
                        r_year = '20' + r_year
                        r_date = r_day + "/" + r_month + "/" + r_year
                        self.dateTxt.setText(r_date)
                        self.timeLCDNumber.display(r_time)
                        r_h, r_m, r_s = r_time.split(':')
                else:
                    break
            except:
                print("An error occurred!")
                self.statusConnectLb.setText("1.Status: ERROR")
                self.connectBtn.setText("Connect")
                self.threadRequestTime = False
                break
    
    
    def closeEvent(self):
        print("close Window")  # In ra thông báo khi cửa sổ đóng
        self.statusCloseWindow = True
        

    def receive_messages(self, client_socket):
        self.threadRecvRunning = True
        while self.threadRecvRunning:
            try:
                message = client_socket.recv(1024).decode('utf-8')
                if message:
                    print(message)
                    if (message == "Server received: connected"):
                        print("Connect OK")
                        self.statusConnectLb.setText("Status: Connected")
                        # self.connectBtn.setEnabled(False)
                        self.connectBtn.setText("Disconnect")
                        self.threadRecvRunning = False
                    elif (message == "Server received: xconnected"):
                        break
                    else:
                        print("ERROR")
                else:
                    break
            except:
                print("An error occurred!")
                self.statusConnectLb.setText("Status: ERROR")
                self.connectBtn.setText("Connect")
                break
    
            
    
    # Thiết lập client
    def start_client(self, host, port):
        self.client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.client.connect((host, port))

        # message_check_receive = client.recv(1024).decode('utf-8')

        # if(message_check_receive == 'OK'):
        #     self.connectBtn.setText("Disconnect")
        
        # Bắt đầu luồng nhận tin nhắn
        thread = threading.Thread(target=self.receive_messages, args=(self.client,))
        thread.start()
        
        message_check_send = "check"
        self.client.send(message_check_send.encode('utf-8'))


        # running = True
        # while running:
        #     # message = input("Enter message: ")
        #     if(self.statusCloseWindow):
        #         self.statusConnectLb.setText("Status: Disconnect")
        #         self.connectBtn.setEnabled(True)
        #         running = False
        #     time.sleep(0.5)
        #     message = '1'
        #     if message.lower() == 'exit':
        #         break
        #     client.send(message.encode('utf-8'))

        # client.close()

#hàm kiểm tra biểu thức chính quy của địa chỉ IPv4
def is_valid_ipv4(ip):
    # Biểu thức chính quy cho địa chỉ IPv4
        pattern = r'^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
        return re.match(pattern, ip) is not None

def is_valid_port(port):
    return isinstance(port, int) and 0 <= port <= 65535

def convert_string(original_string):
    # Chuyển đổi thành chữ thường và thêm phần mở rộng
    return original_string.lower() + '.sgv'
#-------------------------------------------------------

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())