# Form implementation generated from reading ui file '.\QT_ui\gui.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QPoint, QTime, QTimer
from PyQt6.QtGui import QColor, QPolygon, QPainter
import re
import socket
import threading
import time

class AnalogClock(QtWidgets.QWidget):
    secondHand = QPolygon([
        QPoint(7, 8),
        QPoint(-7, 8),
        QPoint(0, -95)
    ])
    hourHand = QPolygon([
        QPoint(7, 8),
        QPoint(-7, 8),
        QPoint(0, -50)
    ])
    minuteHand = QPolygon([
        QPoint(7, 8),
        QPoint(-7, 8),
        QPoint(0, -70)
    ])
    hourColor = QColor(127, 0, 127)
    minuteColor = QColor(0, 100, 250, 200)
    secondColor = QColor(195, 0, 0, 150)

    def __init__(self, parent=None):
        super(AnalogClock, self).__init__(parent)
        timer = QTimer(self)
        timer.timeout.connect(self.update)
        timer.start(1000)
        self.setMinimumSize(200, 200)

    def paintEvent(self, event):
        side = min(self.width(), self.height())
        time = QTime.currentTime()
        painter = QPainter(self)
        painter.translate(self.width() / 2, self.height() / 2)
        painter.scale(side / 200, side / 200)

        # Vẽ giờ
        painter.setBrush(AnalogClock.hourColor)
        painter.save()
        painter.rotate(30.0 * (time.hour() + time.minute() / 60.0))
        painter.drawConvexPolygon(AnalogClock.hourHand)
        painter.restore()

        # Vẽ phút
        painter.setBrush(AnalogClock.minuteColor)
        painter.save()
        painter.rotate(6.0 * (time.minute() + time.second() / 60.0))
        painter.drawConvexPolygon(AnalogClock.minuteHand)
        painter.restore()

        # Vẽ giây
        painter.setBrush(AnalogClock.secondColor)
        painter.save()
        painter.rotate(360 * (time.second() / 60.0))
        painter.drawConvexPolygon(AnalogClock.secondHand)
        painter.restore()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("CLOCK TCP")
        # MainWindow.resize(622, 790)
        MainWindow.setFixedSize(622, 500) #790
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 90, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.areaTxt = QtWidgets.QComboBox(parent=self.centralwidget)
        self.areaTxt.setGeometry(QtCore.QRect(50, 80, 201, 31))
        self.areaTxt.setObjectName("areaTxt")
        self.areaTxt.addItem("")
        self.areaTxt.addItem("")
        self.areaTxt.addItem("")
        self.areaTxt.addItem("")

        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 90, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.timeLCDNumber = QtWidgets.QLCDNumber(parent=self.centralwidget)
        self.timeLCDNumber.setGeometry(QtCore.QRect(60, 200, 141, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.timeLCDNumber.setFont(font)
        self.timeLCDNumber.setObjectName("timeLCDNumber")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.ipServerTxt = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ipServerTxt.setGeometry(QtCore.QRect(140, 40, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ipServerTxt.setFont(font)
        self.ipServerTxt.setObjectName("ipServerTxt")

        self.label_port = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_port.setGeometry(QtCore.QRect(260, 50, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_port.setFont(font)
        self.label_port.setObjectName("label_port")
        self.portServerTxt = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.portServerTxt.setGeometry(QtCore.QRect(300, 40, 60, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.portServerTxt.setFont(font)
        self.portServerTxt.setObjectName("portServerTxt")

        self.connectBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.connectBtn.setGeometry(QtCore.QRect(365, 40, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.connectBtn.setFont(font)
        self.connectBtn.setObjectName("connectBtn")
        self.statusConnectLb = QtWidgets.QLabel(parent=self.centralwidget)
        self.statusConnectLb.setGeometry(QtCore.QRect(450, 50, 200, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.statusConnectLb.setFont(font)
        self.statusConnectLb.setObjectName("statusConnectLb")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.countryTxt = QtWidgets.QComboBox(parent=self.centralwidget)
        self.countryTxt.setGeometry(QtCore.QRect(320, 80, 201, 31))
        self.countryTxt.setObjectName("countryTxt")
        self.countryTxt.addItem("")
        self.countryTxt.addItem("")
        self.countryTxt.addItem("")
        self.countryTxt.addItem("")

        self.dateTxt = QtWidgets.QLabel(parent=self.centralwidget)
        self.dateTxt.setGeometry(QtCore.QRect(60, 170, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dateTxt.setFont(font)
        self.dateTxt.setObjectName("dateTxt")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 200, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.requestBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.requestBtn.setGeometry(QtCore.QRect(530, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.requestBtn.setFont(font)
        self.requestBtn.setObjectName("requestBtn")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 140, 301, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(80, 10, 491, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.flagLB = QtWidgets.QLabel(parent=self.centralwidget)
        self.flagLB.setGeometry(QtCore.QRect(270, 170, 111, 51))
        self.flagLB.setObjectName("flagLB")



        # Thêm đồng hồ vào GUI
        self.clock = AnalogClock(parent=self.centralwidget)
        self.clock.setGeometry(QtCore.QRect(200, 250, 200, 200))  # Điều chỉnh kích thước và vị trí

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 622, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        
        #-------------------------------------------------------
        self.statusCloseWindow = False
        self.threadRecvRunning = False
        self.threadTransRunning = False
        self.clientClose = None
        app.aboutToQuit.connect(self.closeEvent)
        self.connectBtn.clicked.connect(self.connectWithServer)
        self.requestBtn.clicked.connect(self.requestTime)
        #-------------------------------------------------------


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CLOCK"))

        self.label.setText(_translate("MainWindow", "Area:"))
        self.areaTxt.setItemText(0, _translate("MainWindow", "item1"))
        self.areaTxt.setItemText(1, _translate("MainWindow", "item2"))
        self.areaTxt.setItemText(2, _translate("MainWindow", "item3"))
        self.areaTxt.setItemText(3, _translate("MainWindow", "item4"))

        self.label_2.setText(_translate("MainWindow", "Country:"))
        self.countryTxt.setItemText(0, _translate("MainWindow", "item1"))
        self.countryTxt.setItemText(1, _translate("MainWindow", "item2"))
        self.countryTxt.setItemText(2, _translate("MainWindow", "item3"))
        self.countryTxt.setItemText(3, _translate("MainWindow", "item4"))


        self.label_3.setText(_translate("MainWindow", "IPv4 Server connect:"))
        self.label_port.setText(_translate("MainWindow", "Port:"))
        self.connectBtn.setText(_translate("MainWindow", "Connect"))
        self.statusConnectLb.setText(_translate("MainWindow", "Status:"))
        self.label_5.setText(_translate("MainWindow", "Date:"))
        self.dateTxt.setText(_translate("MainWindow", "0:00:0000"))
        self.label_7.setText(_translate("MainWindow", "Time:"))
        self.requestBtn.setText(_translate("MainWindow", "Request"))
        self.label_4.setText(_translate("MainWindow", "RESULTS RETURNED FROM SERVER"))
        self.label_8.setText(_translate("MainWindow", "CLOCK PROGRAM (TCP CLIENT SERVER MODEL)"))
        self.flagLB.setText(_translate("MainWindow", "flag"))

    #-------------------------------------------------------

    def connectWithServer(self):
        if(self.connectBtn.text() == "Connect"):
            print("CONNNECT")
            ip = self.ipServerTxt.text()
            port = int(self.portServerTxt.text())

            if is_valid_ipv4(ip) and is_valid_port(int(port)):
                print(ip, ":", port)
                start_thread = threading.Thread(target=self.start_client, args=(ip,int(port)))
                start_thread.start()
                
            else: 
                self.statusConnectLb.setText("IPv4 ERROR")
        else:
            print("DISCONNECT BTN EVENT")
            self.connectBtn.setText("Connect")
            

    def requestTime(self):
        print("REQUEST TIM BTN EVENT")

        area = self.areaTxt.currentText() 
        country = self.countryTxt.currentText()

        print(area, "-", country)



    def closeEvent(self):
        print("close Window")  # In ra thông báo khi cửa sổ đóng
        self.statusCloseWindow = True
        

    def receive_messages(self, client_socket):
        self.threadRecvRunning = True
        while self.threadRecvRunning:
            try:
                message = client_socket.recv(1024).decode('utf-8')
                if message:
                    print(message)
                    if (message == "Server received: connected"):
                        print("Connect OK")
                        self.statusConnectLb.setText("Status: Connected")
                        # self.connectBtn.setEnabled(False)
                        self.connectBtn.setText("Disconnect")
                        self.threadRecvRunning = False
                    else:
                        print("TIME")
                else:
                    break
            except:
                print("An error occurred!")
                self.statusConnectLb.setText("Status: ERROR")
                self.connectBtn.setEnabled(True)
                break
    
            
    
    # Thiết lập client
    def start_client(self, host, port):
        client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        client.connect((host, port))
        
        # self.clientClose = client

        # message_check_receive = client.recv(1024).decode('utf-8')

        # if(message_check_receive == 'OK'):
        #     self.connectBtn.setText("Disconnect")
        
        # Bắt đầu luồng nhận tin nhắn
        thread = threading.Thread(target=self.receive_messages, args=(client,))
        thread.start()
        
        message_check_send = "check"
        client.send(message_check_send.encode('utf-8'))


        # running = True
        # while running:
        #     # message = input("Enter message: ")
        #     if(self.statusCloseWindow):
        #         self.statusConnectLb.setText("Status: Disconnect")
        #         self.connectBtn.setEnabled(True)
        #         running = False
        #     time.sleep(0.5)
        #     message = '1'
        #     if message.lower() == 'exit':
        #         break
        #     client.send(message.encode('utf-8'))

        # client.close()

#hàm kiểm tra biểu thức chính quy của địa chỉ IPv4
def is_valid_ipv4(ip):
    # Biểu thức chính quy cho địa chỉ IPv4
        pattern = r'^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
        return re.match(pattern, ip) is not None

def is_valid_port(port):
    return isinstance(port, int) and 0 <= port <= 65535

#-------------------------------------------------------

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())